### ISSUE TITLE
Code block border does not match code block area

### ISSUE THREAD

**Issue by jonathanglassman** [alphagov/tech-docs-gem#100]
For example:

https://govukpay-docs-test-jfh.cloudapps.digital/making_payments/#creating-a-payment

![Making payments   Pay](https://user-images.githubusercontent.com/29436951/64270953-59010980-cf34-11e9-9f25-fa060668351a.png)

**Comment by jonheslop** [comment]
Oh weird I didnt understand what you meant by this! What browser were you using because it doesn’t do this in Firefox, which is why I was confused

**Comment by jonathanglassman** [comment]
> Oh weird I didnt understand what you meant by this! What browser were you using because it doesn’t do this in Firefox, which is why I was confused

@jonheslop this happens in Chrome

**Comment by bravegrape** [comment]
@jonheslop also in Safari.

This reminds me of something @christophertomasdesign noticed about the tech docs template when he made a diagram for the docs. He said the text width in the tech docs template is around 100 px  (?) larger than the text width on GOV.UK. Maybe the two are related?

**Comment by jonheslop** [comment]
This issue is caused by 
https://github.com/alphagov/tech-docs-gem/blob/master/lib/assets/stylesheets/modules/_technical-documentation.scss#L122-L126

Which is seems like was a temp fix for another issue. I was just gonna remove the `max-width: 40em` until I saw the comment 🤔 

But @bravegrape you’re probably right that the line length in general is probably too long
