### ISSUE TITLE
Build breaks when duplicate headings are in one repo

### ISSUE THREAD

**Issue by PippaClarkGDS** [alphagov/tech-docs-gem#284]
## What should change

A fix would be for Middleman to class the duplicate headers as distinct underneath their respective H1s (maybe ... there might be another solution)

## User need

This would avoid breaking the build which would be good for users. 

Middleman breaks when there's duplicate headings on different pages.

## Extra detail 

e.g. Team A is on one page with the H1 "Team A" and H2 "Team links", and Team B is on another page with the H1 "Team B" and H2 "Team links".

Would be good to have a fix so Middleman takes into account the page hierarchy and doesn't break. (also I realise this is a rubbish example as you could amend the H2s to "Team A/B links" but hopefully the gist is made)

the dev said Middleman was breaking - was throwing these kinds of errors though so might be html-proofer: "-build/authentication/index.html
* linking to internal hash #get-started-with-the-prove-your-identity-team-team-links that does not exist (line 100)"

Would there be a way to fix so Middleman can class the duplicate headers as distinct underneath their respective H1s?

**Comment by m-green** [comment]
Just wanted to add a bit of context to why we closed this.

This *is* an issue with some GDS builds, that's specifically because those builds are using html-proofer (which isn't part of TDT). html-proofer seems to throw an error when it finds a link to a relative url that has a partial duplicate - such as a duplicate heading.

Although the problem relates to only one tool, it would still be good to fix the root cause because it causes some other problems. However the root cause is already covered and prioritised in another issue: https://github.com/alphagov/tech-docs-gem/issues/150.
